### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by rubenstolk** [localForage/localForage-memoryStorageDriver#1]
- [x] Add bower.json
- [x] Register with bower

**Comment by thgreasi** [comment]
Ok, I will do it tonight!

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer

**Comment by thgreasi** [comment]
@rubenstolk Resolved by fb9aa062d05538a512ea038f2bb6054892142114 . Doesn't yet show up on [bower's web search](http://bower.io/search/?q=localforage-memoryStorageDriver) but works with `bower install localforage-memoryStorageDriver`.
Please re-open in any case (or open a PR). Thanks for the feedback!

**Comment by rubenstolk** [comment]
Nice!!!
