### ISSUE TITLE
impossible to use as immediate fallback

### ISSUE THREAD

**Issue by rubenstolk** [localForage/localForage-memoryStorageDriver#2]
The issue that I solved in the original PR was:
- When the page loads with localforage, localforage works immediately
- Now suppose Safari run in Private Mode, in my PR localforage would immediately fallback to memoryStorage
- With this separate plugin, I first need to run `defineDriver` whereas in the meanwhile my app may already try to consume localforage, therefore this plugin is not yet a drop-in solution.

Suggestion:
- [ ] When this driver loads, immediately add it to the supported drivers of localforage and add it as the last entry of the default drivers array

**Comment by thgreasi** [comment]
That's against the things that a custom driver should do. If you need to use a custom driver, especially in the case of this volatile one, you should explicitly make it available with `defineDriver` yourself.
The changes required for your app shouldn't be that big. Just define and set the driver in your app's primary initialization method.

**Comment by thgreasi** [comment]
Moreover, I think that we can't access the default driver list from a third party piece of code.

**Comment by gabrielmaldi** [comment]
This would be solved by https://github.com/localForage/localForage/pull/692
