### ISSUE TITLE
Is it ok to write ajax driver based on this one?

### ISSUE THREAD

**Issue by YuriGor** [localForage/localForage-memoryStorageDriver#4]
Hi!
I am going to write my own Ajax driver for localforage,
to be able just switch storage from client to server mode and back.
Could you please advise, is it good idea at all,
and is it ok to use this memory driver as blueprint of my own?
Thank you!

**Comment by thgreasi** [comment]
Yes, this should be a good starting point for your use case.
I'm glad you found it useful for such a purpose.
I hope the structure of the project and the rollup bundling will ease you.
Cheers from Greece.

**Comment by john-doherty** [comment]
I realise this is an old post but I wrote something similar that uses the new window.fetch API designed to replace AJAX [offline-fetch](https://github.com/john-doherty/offline-fetch).
