### ISSUE TITLE
undefined is not a function/constructor self.ready()

### ISSUE THREAD

**Issue by mrgenixus** [localForage/localForage-memoryStorageDriver#5]
## I'm not sure I understand the Driver Architecture

After looking at the source code and the localForage source code, I'm unsure why this would work.  It seems that the driver does not define ready and expects to be able to call ready on itself.

I assume this is tested, but I'm unsure why it doesn't work in my application.  Should a driver implement the core API of the library?  should it expect to be able to call localForage's ready method?

just trying to test a thin wrapper for localForage and having a bad time

**Comment by thgreasi** [comment]
Have you checked [the provided examples](https://github.com/localForage/localForage-memoryStorageDriver/tree/master/examples)?

**Comment by mrgenixus** [comment]
Truly, that was what I found most unexpected.  I received the error in the title when using an approximate duplication of the provided example.  Alas, I have used a mock rather than the in-memory driver, but it's not as good.

What `ready` method is the driver calling?

**Comment by thgreasi** [comment]
That's the ready method of LocalForage. When localforage.setDriver is
called, the properties of the driver are attached to the localForage
instance. The inside your method you should expect that `this` will be
equal to the localForage instance.
-- 
*Thodoris Greasidis*
